---
- name: Recreate compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ shaka_app_dir }}"
    state: present
    build: always
    recreate: always
  listen: Recreate compose stack
  when: app_compose_up | bool
