---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: jenkins-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /usr/sbin/init
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      jenkins-instance:
        citools_enable_tls: false
        jenkins_domain: "jenkins.example.com"
verifier:
  name: ansible
